create table EMPREGADO
(
	ID INTEGER not null primary key,
	FIRSTNAME VARCHAR(30) not null,
	LASTNAME VARCHAR(30) not null,
	USERNAME VARCHAR(30) not null unique,
	PASSWORD VARCHAR(30) not null,
	SEX CHAR(1) not null,
	DATEOFBIRTH DATE not null,
	CREATED TIMESTAMP,
	MODIFIED TIMESTAMP
);
create table CATEGORIA
(
	ID INTEGER not null primary key,
	NAME VARCHAR(30) not null unique,
    CREATED TIMESTAMP,
	MODIFIED TIMESTAMP
);
create table SUBCATEGORIA
(
	ID INTEGER not null primary key,
	NAME VARCHAR(30) not null,
	CAT_ID INTEGER not null,
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORIA(ID),
    CREATED TIMESTAMP,
	MODIFIED TIMESTAMP
);
create table PRODUTO
(
	ID INTEGER not null primary key,
	NAME VARCHAR(30) not null,
    EMP_ID INTEGER not null,
	CAT_ID INTEGER not null,
	SUBCAT_ID INTEGER not null,
    FOREIGN KEY (EMP_ID) REFERENCES EMPREGADO(ID),
	FOREIGN KEY (CAT_ID) REFERENCES CATEGORIA(ID),
	FOREIGN KEY (SUBCAT_ID) REFERENCES SUBCATEGORIA(ID),
	CREATED TIMESTAMP,
	MODIFIED TIMESTAMP
);
create table FATURAS
(
	ID INTEGER not null primary key,
	CODE VARCHAR(30) not null unique,
	EMP_ID INTEGER not null,
	PROD_ID INTEGER not null,
	FOREIGN KEY (EMP_ID) REFERENCES EMPREGADO(ID),
	FOREIGN KEY (PROD_ID) REFERENCES PRODUTO(ID),
    CREATED TIMESTAMP,
	MODIFIED TIMESTAMP
);
create table LINHASDEFATURAS
(
	ID INTEGER not null primary key,
	LINE VARCHAR(30),
	VALUE DECIMAL not null, 
	FAT_ID INTEGER not null,
    FOREIGN KEY (FAT_ID) REFERENCES FATURAS(ID),	
    CREATED TIMESTAMP,
	MODIFIED TIMESTAMP
);
